version: '3.8'

services:
  app:
    image: nshlyakhtin/devops:lab12-app-python-arm64
    volumes:
      - visits_data:/app/data
    ports:
      - "5000:5000"

volumes:
  visits_data:
    driver: local