global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'moscow-time-app'
    static_configs:
      - targets: ['moscow-time-app:5000']

  - job_name: 'crypto_price_tracker'
    static_configs:
      - targets: ['crypto_price_tracker:8080']
