apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time-app
  template:
    metadata:
      labels:
        app: moscow-time-app
    spec:
      containers:
        - name: app-python
          image: nshlyakhtin/devops:lab8-app-python-amd64
          ports:
            - containerPort: 5000