apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-post-install-hook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: post-install
      image: alpine:latest
      command: [ "/bin/sh", "-c" ]
      args: [ "echo 'Post-install hook'; sleep 20" ]