apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: pre-install
      image: alpine:latest
      command: [ "/bin/sh", "-c" ]
      args: [ "echo 'Pre-install hook'; sleep 20" ]