apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "moscow-time-app.fullname" . }}
  labels:
    {{- include "moscow-time-app.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.statefulSet.serviceName }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "moscow-time-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "moscow-time-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MY_SECRET
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: data-volume
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi